const fields=['tipo','categoria','modelo','serie','patrimonio','imei','hostname','local','etiqueta','usuario','status','origem','observacao'];
const $=id=>document.getElementById(id);let equipamentos=[];let db=null;let auth=null;let unsub=null;let currentUser=null;const COLLECTION='equipamentos';
function uid(){return 'eq_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function normalize(x){return {id:x.id||uid(),tipo:x.tipo||'Outro',categoria:x.categoria||'',modelo:x.modelo||'',serie:x.serie||'',patrimonio:x.patrimonio||'',imei:x.imei||'',hostname:x.hostname||'',local:x.local||'',etiqueta:x.etiqueta||'',usuario:x.usuario||'',status:x.status||'Ativo',origem:x.origem||'',observacao:x.observacao||'',atualizadoEm:x.atualizadoEm||new Date().toISOString(),atualizadoPor:x.atualizadoPor||''}}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function badgeClass(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s/g,'')}
function configOk(){const c=window.FIREBASE_CONFIG||{};return c.apiKey&&c.projectId&&!String(c.apiKey).includes('COLE_AQUI')&&!String(c.projectId).includes('COLE_AQUI')}
function initFirebase(){if(!configOk()){showLoginMsg('Configure o arquivo firebase-config.js antes de usar o banco online.');return}firebase.initializeApp(window.FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(user=>{currentUser=user;if(user){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');listenFirestore();}else{$('loginScreen').classList.remove('hidden');$('app').classList.add('hidden');}})}
function showLoginMsg(msg){$('loginMsg').textContent=msg||''}
$('btnEntrar').onclick=async()=>{try{showLoginMsg('');await auth.signInWithEmailAndPassword($('loginEmail').value.trim(),$('loginSenha').value)}catch(e){showLoginMsg('Erro ao entrar: '+traduzErro(e.code))}}
$('btnCadastrar').onclick=async()=>{try{showLoginMsg('');await auth.createUserWithEmailAndPassword($('loginEmail').value.trim(),$('loginSenha').value);alert('Usuário criado com sucesso!')}catch(e){showLoginMsg('Erro ao criar usuário: '+traduzErro(e.code))}}
$('btnSair').onclick=()=>auth.signOut();
function traduzErro(code){return {'auth/invalid-email':'e-mail inválido','auth/missing-password':'informe a senha','auth/weak-password':'senha muito fraca','auth/email-already-in-use':'este e-mail já existe','auth/invalid-credential':'e-mail ou senha incorretos'}[code]||code}
function listenFirestore(){if(unsub)unsub();$('syncStatus').textContent='Conectado ao Firebase';unsub=db.collection(COLLECTION).orderBy('tipo').onSnapshot(snap=>{equipamentos=snap.docs.map(d=>normalize({id:d.id,...d.data()}));renderAll();},err=>{$('syncStatus').textContent='Erro no Firebase';alert('Erro ao ler Firebase: '+err.message)})}
async function salvarEquipamento(data,id){data.atualizadoEm=new Date().toISOString();data.atualizadoPor=currentUser?.email||'';if(id) await db.collection(COLLECTION).doc(id).set(data,{merge:true}); else await db.collection(COLLECTION).doc(data.id||uid()).set(normalize(data));}
async function excluirEquipamento(id){await db.collection(COLLECTION).doc(id).delete()}
function getFiltered(){const q=$('busca').value.toLowerCase().trim(),tipo=$('filtroTipo').value,st=$('filtroStatus').value,loc=$('filtroLocal').value;return equipamentos.filter(e=>{const hay=fields.map(f=>e[f]).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!tipo||e.tipo===tipo)&&(!st||e.status===st)&&(!loc||e.local===loc)})}
function renderTable(){const rows=getFiltered();$('contadorLista').textContent=rows.length+' itens listados';$('tbody').innerHTML=rows.map(e=>`<tr><td><b>${escapeHtml(e.tipo)}</b><br><small>${escapeHtml(e.origem)}</small></td><td>${escapeHtml(e.modelo)}<br><small>${escapeHtml(e.categoria)}</small></td><td><b>${escapeHtml(e.serie)}</b>${e.imei?'<br><small>IMEI: '+escapeHtml(e.imei)+'</small>':''}</td><td>${escapeHtml(e.patrimonio)}</td><td>${escapeHtml(e.hostname)}</td><td>${escapeHtml(e.local)}</td><td>${escapeHtml(e.etiqueta)}</td><td>${escapeHtml(e.usuario)}</td><td><span class="badge ${badgeClass(e.status)}">${escapeHtml(e.status)}</span></td><td><div class="row-actions"><button class="edit" onclick="editItem('${e.id}')">Editar</button><button class="delete" onclick="deleteItem('${e.id}')">Excluir</button></div></td></tr>`).join('')||'<tr><td colspan="10">Nenhum equipamento encontrado.</td></tr>'}
function fillSelect(id,values,label){const cur=$(id).value;$(id).innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option ${v===cur?'selected':''}>${escapeHtml(v)}</option>`).join('')}
function renderFilters(){const tipos=[...new Set(equipamentos.map(e=>e.tipo).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));const locais=[...new Set(equipamentos.map(e=>e.local).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));const sts=[...new Set(['Ativo','Reserva','Emprestado','Manutenção','Baixado','Sem patrimônio',...equipamentos.map(e=>e.status).filter(Boolean)])];fillSelect('filtroTipo',tipos,'Todos os tipos');fillSelect('filtroLocal',locais,'Todos os locais');fillSelect('filtroStatus',sts,'Todos os status');$('listaLocais').innerHTML=locais.map(l=>`<option value="${escapeHtml(l)}"></option>`).join('')}
function renderKpis(){const count=t=>equipamentos.filter(e=>e.tipo===t).length;$('kpiTotal').textContent=equipamentos.length;$('kpiTablets').textContent=count('Tablet');$('kpiNotebooks').textContent=count('Notebook');$('kpiComputadores').textContent=count('Computador');$('kpiSmartphones').textContent=count('Smartphone');$('kpiLocais').textContent=new Set(equipamentos.map(e=>e.local).filter(Boolean)).size}
function renderAll(){renderFilters();renderKpis();renderTable()}
function clearForm(){ $('editId').value=''; fields.forEach(f=>$(f).value=f==='tipo'?'Tablet':(f==='status'?'Ativo':'')); $('formTitle').textContent='Novo equipamento'}
window.editItem=id=>{const e=equipamentos.find(x=>x.id===id);if(!e)return;$('editId').value=id;fields.forEach(f=>$(f).value=e[f]||'');$('formTitle').textContent='Editando equipamento';scrollTo({top:0,behavior:'smooth'})}
window.deleteItem=async id=>{if(confirm('Deseja excluir este equipamento do Firebase?')) await excluirEquipamento(id)}
$('equipForm').addEventListener('submit',async ev=>{ev.preventDefault();const id=$('editId').value;const data={};fields.forEach(f=>data[f]=$(f).value.trim());await salvarEquipamento(data,id);clearForm();});
$('btnLimpar').addEventListener('click',clearForm);['busca','filtroTipo','filtroStatus','filtroLocal'].forEach(id=>$(id).addEventListener('input',renderTable));
function csvEscape(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function exportCsv(){const headers=['Tipo','Categoria','Modelo','Número de Série','Patrimônio','IMEI','Hostname','Local','Etiqueta','Usuário/Responsável','Status','Origem','Observação','Atualizado em','Atualizado por'];const lines=[headers.map(csvEscape).join(';')].concat(equipamentos.map(e=>[e.tipo,e.categoria,e.modelo,e.serie,e.patrimonio,e.imei,e.hostname,e.local,e.etiqueta,e.usuario,e.status,e.origem,e.observacao,e.atualizadoEm,e.atualizadoPor].map(csvEscape).join(';')));download(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),'inventario-equipamentos.csv')}
function exportJson(){download(new Blob([JSON.stringify(equipamentos,null,2)],{type:'application/json'}),'backup-inventario-firebase.json')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function parseCsv(text){const rows=[];let row=[],val='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){val+='"';i++}else if(c==='"'){quote=!quote}else if((c===';'||c===',')&&!quote){row.push(val);val=''}else if((c==='\n'||c==='\r')&&!quote){if(val||row.length){row.push(val);rows.push(row);row=[];val=''}if(c==='\r'&&n==='\n')i++}else val+=c}if(val||row.length){row.push(val);rows.push(row)}return rows}
$('importFile').addEventListener('change',async ev=>{const file=ev.target.files[0];if(!file)return;const text=await file.text();try{let arr;if(file.name.toLowerCase().endsWith('.json')) arr=JSON.parse(text).map(normalize); else {const rows=parseCsv(text).filter(r=>r.length>1);arr=rows.slice(1).map(r=>normalize({tipo:r[0],categoria:r[1],modelo:r[2],serie:r[3],patrimonio:r[4],imei:r[5],hostname:r[6],local:r[7],etiqueta:r[8],usuario:r[9],status:r[10]||'Ativo',origem:r[11],observacao:r[12],atualizadoEm:r[13],atualizadoPor:r[14]}))}await importarLote(arr);alert('Importação concluída!')}catch(e){alert('Não foi possível importar: '+e.message)}ev.target.value=''})
async function importarLote(arr){let batch=db.batch(),count=0;for(const raw of arr){const e=normalize(raw);batch.set(db.collection(COLLECTION).doc(e.id),e,{merge:true});count++;if(count%450===0){await batch.commit();batch=db.batch()}}await batch.commit()}
$('btnImportarFirebase').onclick=async()=>{if(!confirm('Enviar os dados iniciais das planilhas para o Firebase? Use apenas na primeira configuração.'))return;await importarLote((window.DADOS_INICIAIS||[]).map(normalize));alert('Dados iniciais enviados para o Firebase!')}
$('btnExportCsv').addEventListener('click',exportCsv);$('btnExportJson').addEventListener('click',exportJson);
initFirebase();
